-- MySQL Script generated by MySQL Workbench
-- Mon May 29 18:16:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lorenzasCoffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lorenzasCoffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lorenzasCoffee` DEFAULT CHARACTER SET utf8 ;
USE `lorenzasCoffee` ;

-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`empleado` (
  `rfc` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  PRIMARY KEY (`rfc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`tiposEmpleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`tiposEmpleados` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`empleado_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`empleado_tipo` (
  `rfc_empleado` VARCHAR(20) NOT NULL,
  `id_tipo_empleado` INT NOT NULL,
  CONSTRAINT `fk_tipo_emp_idTipo`
    FOREIGN KEY (`id_tipo_empleado`)
    REFERENCES `lorenzasCoffee`.`tiposEmpleados` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_emp_idEmpleado`
    FOREIGN KEY (`rfc_empleado`)
    REFERENCES `lorenzasCoffee`.`empleado` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`operaciones` (
  `id_operacion` INT NOT NULL AUTO_INCREMENT,
  `operacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`registros` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `rfc_empleado` VARCHAR(20) NULL,
  `id_operacion` INT NULL,
  PRIMARY KEY (`id_registro`),
  CONSTRAINT `fk_registro_rfc`
    FOREIGN KEY (`rfc_empleado`)
    REFERENCES `lorenzasCoffee`.`empleado` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_operacion`
    FOREIGN KEY (`id_operacion`)
    REFERENCES `lorenzasCoffee`.`operaciones` (`id_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`ventas` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `id_registro` INT NULL,
  PRIMARY KEY (`idventa`),
  CONSTRAINT `fk_vent_idregistro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `lorenzasCoffee`.`registros` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cantidad` FLOAT NULL,
  `caducidad` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `precio_compra` FLOAT NULL,
  `precio_venta` FLOAT NULL,
  `unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`listaProductosVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`listaProductosVenta` (
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  CONSTRAINT `fk_list_v_id_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `lorenzasCoffee`.`ventas` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_v_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lorenzasCoffee`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`resgistro_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`resgistro_tipo` (
  `id_registro` INT NOT NULL,
  `id_tipo` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`insumos` (
  `id_insumo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `costo` FLOAT NULL,
  `estado` VARCHAR(45) NULL,
  `cantidad` FLOAT NULL,
  `caducidad` DATE NULL,
  `unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`producto_insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`producto_insumos` (
  `id_producto` INT NOT NULL,
  `id_insumo` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  CONSTRAINT `fk_ins_prod_idproducto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lorenzasCoffee`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ins_prod_idinsumo`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `lorenzasCoffee`.`insumos` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`idticket`),
  CONSTRAINT `fk_ticket_v_idVenta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `lorenzasCoffee`.`ventas` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `rfc_usuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `iva` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `id_ticket` INT NULL,
  PRIMARY KEY (`id_factura`),
  CONSTRAINT `fk_factura_idTicket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `lorenzasCoffee`.`ticket` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`ordenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`ordenCompra` (
  `id_orden_compra` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NULL,
  `total` FLOAT NULL,
  `id_registro` INT NULL,
  PRIMARY KEY (`id_orden_compra`),
  CONSTRAINT `fk_ord_comp_idreg`
    FOREIGN KEY (`id_registro`)
    REFERENCES `lorenzasCoffee`.`registros` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ord_comp_idprov`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `lorenzasCoffee`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lorenzasCoffee`.`listaProductosCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lorenzasCoffee`.`listaProductosCompras` (
  `id_orden_compra` INT NOT NULL,
  `id_producto` INT NULL,
  `id_insumo` INT NULL,
  `cantidad_pruducto` FLOAT NULL,
  `cantidad_insumo` FLOAT NULL,
  CONSTRAINT `fk_list_c_orden_compra`
    FOREIGN KEY (`id_orden_compra`)
    REFERENCES `lorenzasCoffee`.`ordenCompra` (`id_orden_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_c_idproducto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `lorenzasCoffee`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_c_idinsumo`
    FOREIGN KEY (`id_insumo`)
    REFERENCES `lorenzasCoffee`.`insumos` (`id_insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
